docs/requirements.txt

Currently, all of the output on the website is just a series of uncaught exceptions...

scikit-learn is needed for the PCA notebook

---

MDTraj/formats/pdb/data/pdbNames.xml

A small step towards addressing #637 , which I still think is a big problem

Include tip3 water

---

devtools/conda-recipe/meta.yaml

version number to 1.3.0.dev0

---

MDTraj/core/selection.py
MDTraj/core/topology.py
MDTraj/tests/test_selection.py

This PR fixes the bugs reported in https://github.com/mdtraj/mdtraj/issues/695
Also, when I tried to install mdtraj from source using `python setup.py develop` in a conda environment, I was getting a message that `mdtraj` was not installed, even after the install process looked ok. Do other devs use this method of working on mdtraj? This is how I've worked with MSMBuilder recently and there everything works as expected.

Fixed bugs in backbone and sidechain selection

---

docs/analysis.rst
mdtraj/formats/mdcrd.py
mdtraj/geometry/hbond.py
mdtraj/testing/testing.py

- fix mdcrd issue on py27 windows related to seeking in text/bytes.
- fix 32-bit issue on py27 with int/long.

[WIP] fix #701

---

mdtraj/utils/test.py
mdtraj/utils/unitcell.py

Fix for issue #713. If anyone has more tests, that would be good too.

Bugfix for utils.unitcell.length_and_angles_to_box_vectors

---

mdtraj/formats/gro.py
mdtraj/tests/test_gro.py

This a fix that should address https://github.com/mdtraj/mdtraj/issues/721 and several other issues that weren't immediately obvious from the reported traceback.

Fix gro loading for issue 721

---

mdtraj/core/selection.py
mdtraj/tests/test_selection.py

[ENH] Don't allow bare literals in selection expressions

---

mdtraj/core/topology.py
mdtraj/formats/psf.py
mdtraj/tests/test_psf.py

This addresses #711.  Also fixes a few typos and docstring mistakes.
Tests have been added.

Enhance PSF file topology creation

---

mdtraj/core/residue_names.py
mdtraj/core/topology.py

Move water residue names to residue_names.py

---

README.md
docs/index.rst

Re #712. @cxhernandez what do you think about citation for the preprint vs. the zenodo github code itself?

[DOCS] Add citation to docs and readme

---

devtools/README.md
devtools/conda-recipe/meta.yaml
docs/whatsnew.rst
setup.py

Release 1.3.0

---

docs/faq.rst

Not just CC=gcc44 but also CXX=g++44

Compile on vsp-compute needs g++44 too

---

docs/faq.rst

Update CentOS 5 instructions

---

docs/sphinxext/notebook_sphinxext.py
examples/WebGL-Viewer.ipynb
examples/atom-selection.ipynb
examples/centroids.ipynb
examples/clustering.ipynb
examples/hbonds.ipynb
examples/iterload.ipynb
examples/native-contact.ipynb
examples/nmr.ipynb
examples/principle-components.ipynb
examples/ramachandran-plot.ipynb
examples/rmsd-benchmark.ipynb
examples/rmsd-drift.ipynb
examples/simulation-with-openmm.ipynb
examples/solvent-accessible-surface-area.ipynb
examples/two-pass-clustering.ipynb

Update notebook examples to py3, running with IPython3.

MAINT: Update notebook examples to py3

---

mdtraj/core/trajectory.py

Kind of trivial but there's one for residues and not chains.

n_chains convenience function for traj

---

mdtraj/core/topology.py
mdtraj/geometry/rdf.py
mdtraj/geometry/tests/test_rdf.py
mdtraj/tests/test_topology.py

It should be possible to pre-compute your own pairs for the RDF calculation.

Option to pre-compute pairs for RDF

---

docs/atom_selection.rst
mdtraj/core/selection.py
mdtraj/tests/test_selection.py

Add chainid to DSL

---

mdtraj/core/trajectory.py
mdtraj/formats/pdb/pdbfile.py
mdtraj/tests/test_trajectory.py

pdb.gz was already supported in the underlying code, but it was not registered correctly.

Support .pdb.gz files and make loading multiple pdb files more efficient

---

mdtraj/formats/dcd/dcd.pyx

BUG: Fix garbage in DCD out filename

---

mdtraj/core/trajectory.py
mdtraj/formats/gro.py

ENH: Add save_gro

---

mdtraj/core/topology.py

DOC: Comment about atom.serial

---

.travis.yml
docs/installation.rst
mdtraj/nmr/shift_wrappers.py

Discussed a little bit in #810.

MAINT: Increase minimum required python version to 2.7

---

devtools/travis-ci/update-versions.py

Copy of https://github.com/msmbuilder/msmbuilder/pull/550, for the corresponding script in this repo.

Fix update-versions.py script, porting msmbuilder#550

---

mdtraj/core/element.py

I used the radii from the vmd source code:
https://github.com/thatchristoph/vmd-cvs-github/blob/ff3c1b70fd62600fa29ba79819f5312980939a2a/vmd/src/PeriodicTable.C
The new source code was built programmatically with the following script, so as not to make any data entry mistakes.
```
$ cat ../build_table.py
symbols = [
"X",  "H",  "He", "Li", "Be", "B",  "C",  "N",  "O",  "F",  "Ne",
"Na", "Mg", "Al", "Si", "P" , "S",  "Cl", "Ar", "K",  "Ca", "Sc",
"Ti", "V",  "Cr", "Mn", "Fe", "Co", "Ni", "Cu", "Zn", "Ga", "Ge",
"As", "Se", "Br", "Kr", "Rb", "Sr", "Y",  "Zr", "Nb", "Mo", "Tc",
"Ru", "Rh", "Pd", "Ag", "Cd", "In", "Sn", "Sb", "Te", "I",  "Xe",
"Cs", "Ba", "La", "Ce", "Pr", "Nd", "Pm", "Sm", "Eu", "Gd", "Tb",
"Dy", "Ho", "Er", "Tm", "Yb", "Lu", "Hf", "Ta", "W",  "Re", "Os",
"Ir", "Pt", "Au", …
```

ENH: Add full list of van der Waals radii

---

docs/requirements.txt

MAINT: Pin sphinx version to avoid regression.

---

mdtraj/core/trajectory.py
mdtraj/formats/gro.py
mdtraj/tests/test_gro.py

This incoporates https://github.com/mdtraj/mdtraj/pull/832 and fixes the tests so that the previous error was caught.

BUGFIX: Fix gro file unitcell handling 

---

devtools/README.md

I made these changes in March apparently but never PR'ed them

Update instructions for doing a release

---

devtools/README.md

Typo in doing a release

---

devtools/authors.py
devtools/conda-recipe/meta.yaml
docs/whatsnew.rst
setup.py

This PR updates the version numbers to cut the 1.4.0 release. After merging, I'll tag this as the release.
I also added a new script to `devtools/` taken from scipy for getting the author list out of the git log, which I used for making the release notes.

Release 1.4.0

---

mdtraj/geometry/angle.py

Fix small (probably copy-paste) error in documentation string.

Fix docstring

---

mdtraj/html/__init__.py
mdtraj/html/trajectory_widget.py

As discussed in https://github.com/mdtraj/mdtraj/issues/863

Added TrajectorySliderView

---

.checkignore
mdtraj/core/trajectory.py
mdtraj/formats/hdf5.py
mdtraj/formats/hoomdxml.py
mdtraj/formats/pdb/pdbfile.py
mdtraj/formats/pdb/pdbstructure.py

Check it out: https://www.quantifiedcode.com/app/project/47b999d7e38e4c05bce97fced0469c4e
Seems pretty neat.  Not sure how useful it is, but it gives some interesting statistics and code diagnostics.
Hai from my group showed me this site.

ENH: Some minor fixes suggested by QuantifiedCode.

---

devtools/README.md

Hi,
I add .travis.yml file to BSD license too.
thanks
Hai

add BSD license to ./devtools folder and .travis.yml file

---

mdtraj/core/topology.py
mdtraj/tests/test_topology.py

This fixes the same issue as #886.

Fix n_residues set by _topology_from_subset

---

mdtraj/core/topology.py
mdtraj/core/trajectory.py
mdtraj/tests/test_trajectory.py

Fixes merge conflicts with #843

Add hash implementation

---

mdtraj/formats/dcd/include/fastio.h

bugfix/dcdreader: fix sharing mode under Windows

---

devtools/travis-ci/install.sh
devtools/travis-ci/update-versions.py

Fix openmm-dev package uploads to binstar

---

.travis.yml
devtools/conda-recipe/README.md
devtools/travis-ci/after_sucess.sh

Fix dev upload

---

.travis.yml
devtools/conda-recipe/meta.yaml

Also get rid of py2.6 stuff, as we haven't been building 2.6 conda packages for a while

Update conda packaging

---

README.md
docs/index.rst

Congrats all, the mdtraj paper is now available online: http://www.cell.com/biophysj/abstract/S0006-3495(15)00826-7

Update BibTeX reference

---

setup.py

Force clang on darwin

---

README.md
docs/index.rst

Order is different in the actual paper.

Updated author list in reference.

---

mdtraj/tests/test_mol2.py

Import naming collision

---

devtools/travis-ci/install.sh

Might as well switch to python 3 while we're at it

Miniconda changed default install path

---

appveyor.yml

Fix appveyor breaking

---

mdtraj/geometry/dihedral.py
mdtraj/geometry/tests/test_geometry.py

Compute dihedral indices separately

---

mdtraj/geometry/dihedral.py
mdtraj/geometry/tests/test_dihedral.py

Fix typo in dihedral refactoring

---

mdtraj/formats/pdb/pdbfile.py
mdtraj/formats/pdb/tests/test_pdb.py

Add CONECT bonds based on last model, not first

---

docs/whatsnew.rst
mdtraj/formats/hdf5.py
mdtraj/formats/lh5.py

Remove ensure_mode() decorator

---

mdtraj/formats/xyzfile.py
mdtraj/tests/test_xyz.py

Support __len__ in xyz files

---

mdtraj/formats/hdf5.py

I find this warning from #1002 rather annoying.

Remove annoying warning

---

mdtraj/formats/hdf5.py
mdtraj/rmsd/_rmsd.pyx
mdtraj/rmsd/src/euclidean_permutation.cpp
mdtraj/tests/test_rmsd_memmap.py

This fixes some more of what used to be in #550.

Clean up some cython code to use typed memoryviews

---

mdtraj/utils/__init__.py

Sorry for all the pain I caused you, @mpharrigan.

Remove very annoying warnings filter

---

docs/analysis.rst

Add three NMR functions to documentation

---

.travis.yml
docs/installation.rst
mdtraj/core/trajectory.py
mdtraj/formats/binpos/binpos.pyx
mdtraj/formats/lammpstrj.py
mdtraj/formats/mdcrd.py
mdtraj/formats/xtc/trr.pyx
mdtraj/formats/xtc/xtc.pyx
mdtraj/testing/testing.py
mdtraj/tests/test_trajectory.py

Force overwrite check 

---

docs/whatsnew.rst

Speak soon with any comments on wording or content or forever hold your peace

Update changelog for 1.6

---

devtools/travis-ci/update-versions.py

Fix `update-versions.py`

---

docs/requirements.txt
examples/WebGL-Viewer.ipynb
examples/atom-selection.ipynb
examples/centroids.ipynb
examples/clustering.ipynb
examples/hbonds.ipynb
examples/iterload.ipynb
examples/native-contact.ipynb
examples/nmr.ipynb
examples/principal-components.ipynb
examples/ramachandran-plot.ipynb
examples/rmsd-benchmark.ipynb
examples/rmsd-drift.ipynb
examples/simulation-with-openmm.ipynb
examples/solvent-accessible-surface-area.ipynb
examples/two-pass-clustering.ipynb

Fix example notebooks

---

devtools/travis-ci/after_sucess.sh

I'd like to make e.g. a 1.6 branch that can update the docs for 1.6
I'd also like to keep the branches on mdtraj/mdtraj clean cc #550 #553

Allow doc deployment on other branches

---

devtools/travis-ci/after_sucess.sh
docs/requirements.txt
docs/whatsnew.rst
examples/WebGL-Viewer.ipynb
examples/atom-selection.ipynb
examples/centroids.ipynb
examples/clustering.ipynb
examples/hbonds.ipynb
examples/iterload.ipynb
examples/native-contact.ipynb
examples/nmr.ipynb
examples/principal-components.ipynb
examples/ramachandran-plot.ipynb
examples/rmsd-benchmark.ipynb
examples/rmsd-drift.ipynb
examples/simulation-with-openmm.ipynb
examples/solvent-accessible-surface-area.ipynb
examples/two-pass-clustering.ipynb

backport #1050 to a 1.6 branch (note merge destination)
This requires #1051

Backport changes to example notebooks

---

docs/examples/solvent-accessible-surface-area.rst

Fix typo Sccessible -> Accessible

Fix typo Sccessible -> Accessible

---

mdtraj/core/topology.py
mdtraj/core/trajectory.py
mdtraj/geometry/__init__.py
mdtraj/geometry/distance.py
mdtraj/geometry/include/geometry.h
mdtraj/geometry/src/_geometry.pyx
mdtraj/geometry/src/geometry2.cpp
mdtraj/geometry/tests/test_distance.py
mdtraj/tests/test_topology.py
setup.py

This implementation should be considered preliminary.  It hasn't been at all thoroughly tested.  I tried it on various PDB files and it always seemed to do something reasonable, but I didn't have anything especially challenging on hand.  I'd really like to see how it handles a long simulation of a large complex, or something like that.  So if you have any good test cases, please try it out.
I also added a method to Topology for identifying molecules based on bonds.  I needed it for this feature, and since it seemed a generally useful thing to have, I made it pubic.
Is `image_molecules()` a good name?  Any ideas for a better one?

[WIP] Created function for imaging molecules

---

.travis.yml
devtools/travis-ci/update_versions_json.py

Fixes for doc rework

---

devtools/conda-recipe/meta.yaml
mdtraj/core/topology.py
mdtraj/reporters/basereporter.py
mdtraj/tests/test_reporter.py

Based off of the first two commits of #1088 
@jchodera let me know what you think

Fix segment_id issues take 3

---

basesetup.py
setup.py

Makes a pep440 development version string, and sundry stylistic
trajectories

Update writing version.py

---

README.md

re: https://github.com/mdtraj/mdtraj/issues/1091

Add Depsy badge

---

mdtraj/core/topology.py
mdtraj/core/trajectory.py

Fixed errors in image_molecules() for topologies without bonds

---

.gitignore
basesetup.py

[basesetup] copy contents of export_include and static lib to src tree.

---

devtools/README.md

Update notes on creating a release

---

docs/load_functions.rst
mdtraj/core/trajectory.py
mdtraj/tests/test_trajectory.py

Avoid
```python
traj = None
for i in whatever:
if traj is None:
traj = md.load(i)
else:
traj += md.load(i)
```

Add md.join(trajs)

---

mdtraj/formats/tng/tng.pyx

Check that file exists before trying to open it

---

mdtraj/geometry/neighbors.pyx

Ensure box vectors have right dtype

---

examples/simulation-with-openmm.ipynb

Fix typos and update wording for clarity

Update wording for simulation-with-openmm.ipynb

---

mdtraj/core/trajectory.py

Remove unnecessary restriction

---

README.md
devtools/conda-recipe/meta.yaml

* Fixes broken `binstar` version badge
* Adds anaconda downloads badge
Preview [here](https://github.com/jchodera/mdtraj/blob/a47d0f5c60798488fc96370b29c0c6ad22f7dba0/README.md)

Fix broken binstar badge in README.md

---

mdtraj/tests/test_io.py

Modernize test_io.py

---

mdtraj/core/topology.py
mdtraj/core/trajectory.py

Move guess_anchor_molecules to Topology

---

devtools/travis-ci/build_docs.sh

fixes #1152
The problem was fixed upstream by sphinx

Fix doc search problem

---

mdtraj/core/topology.py

image_molecules already has a see also

Add see also to guess_anchor_molecules

---

devtools/conda-recipe/bld.bat
devtools/conda-recipe/build.sh
devtools/conda-recipe/meta.yaml
devtools/travis-ci/build_docs.sh
docs/requirements.txt

Use test/source_files to run example notebooks. Bring the rest
of it in sync with msmbuilder recipe and conda-forge recipe
addresses CI issue raised in #1227

Fix conda test running

---

mdtraj/geometry/alignment.py
mdtraj/tests/test_rmsd.py

Implemented compute_average_structure()

---

mdtraj/geometry/contact.py
mdtraj/geometry/tests/test_contact.py

Added option to calculate contacts using a diffrentialable scheme when using the residue contact distance option.

added diffrentialable contacts option

---

mdtraj/formats/xtc/xtc.pyx

[xtc] approx_nframes returns at least one.

---

mdtraj/geometry/dihedral.py
mdtraj/geometry/tests/test_dihedral.py

sometimes one is literally interested in all dihedrals, which includes chi5 as well. cc @giopina

added chi5 angle computation

---

mdtraj/formats/xtc/trr.pyx
mdtraj/formats/xtc/trrlib.pxd
tests/test_trr.py

This is a rebase of #1271 
I also modified the tests to work with pytest after #1266 
cc @dwhswenson

 Extracting velocities/forces from TRR files (hidden API) - Rebase

---

mdtraj/core/selection.py
tests/test_selection.py

This is incomplete. I don't have much time to work on it right now if someone wants to take a stab at debugging it

Add "in" selection to selection language

---

mdtraj/nmr/shift_wrappers.py

Rebase of #1246 
Switch from `os.system` to `subprocess`
Switch some of the pandas readings to `sep='\s+'` so it can use the c backend (for speed)
cc @smsaladi

Handle a single frame being passed to sparta+ - Rebase

---

mdtraj/geometry/dssp.py
mdtraj/geometry/hbond.py

Somebody has to do the heavy lifting here...;)

fixed typo in Kabsch-Sander paper

---

mdtraj/formats/dcd/dcd.pyx
tests/test_dcd.py

Revert "[formats/dcd] handle stride like numpy"

---

mdtraj/scripts/mdconvert.py

saves mdconvert users some headaches

correct mdconvert error message

---

docs/whatsnew.rst
setup.py

re: https://github.com/mdtraj/mdtraj/issues/1362

Release v1.9.2

---

setup.py

[setup] do not enforce clang/std++ on osx

---

mdtraj/formats/xtc/include/xdr_seek.h
mdtraj/formats/xtc/src/xdr_seek.c
mdtraj/formats/xtc/xdrlib.pxd
mdtraj/formats/xtc/xtc.pyx
mdtraj/reporters/__init__.py
mdtraj/reporters/xtcreporter.py
setup.py
tests/test_docstrings.py
tests/test_reporter.py
tests/test_xtc.py

Add an XTCReporter for OpenMM with support for atom subsets and append mode.

Add XTCReporter for OpenMM 

---

mdtraj/rmsd/_rmsd.pyx

allow RMSD calls when ref_atom_indices and atom_indices are used

---

docs/analysis.rst
mdtraj/__init__.py
mdtraj/rmsd/_rmsd.pyx
tests/test_rmsd.py

add RMSF analysis

---

appveyor.yml
devtools/conda-recipe/meta.yaml

I forgot exactly the github thread I found this fix from, but it worked for us in https://github.com/mosdef-hub/mbuild/pull/477 so it should work here

Fix appveyor

---

pytest.ini
tests/test_reporter.py

Fix a test failure in test_reporters.py caused by merge of #1431

---

basesetup.py
mdtraj/formats/tng/tng.pyx
mdtraj/formats/xtc/trr.pyx
mdtraj/formats/xtc/xtc.pyx
setup.py

Fix egg info

---

mdtraj/formats/xtc/xtc.pyx
tests/test_xtc.py

[xtc] Fix bugs in striding with atom_indices and seek+stride

---

docs/whatsnew.rst
setup.py

* updated whats new
* set version number in setup

release 1.9.3

---

mdtraj/formats/netcdf.py

Fixing 'stride' parameter for '.netcdf' files

---

mdtraj/core/trajectory.py

Same error as in PR #1466, but this time in make_molecules_whole.

int32_t error strikes again

---

devtools/azure-pipelines-osx.yml
tests/test_pdb.py

Fixing one upstream issue while working on #1423, not sure if this will fix everything but I'm starting with one failing unit test

Try to get green check mark on AZP

---

docs/whatsnew.rst

Should finish the release tomorrow

Add release notes for v1.9.4

---

mdtraj/formats/gro.py

https://github.com/mdtraj/mdtraj/issues/1301

Fix issue #1301

---

mdtraj/core/topology.py
tests/test_topology.py

solves #1585 
Added that example as a test

Fix residue idx sliced traj

---

devtools/azure-pipelines-win.yml
mdtraj/formats/xtc/xtc.pyx

Fix uninitialized variable

---

mdtraj/geometry/shape.py
tests/test_shape.py

Fixes typos in shape.py

---

docs/whatsnew.rst
setup.py

v1.9.6 release notes

---

mdtraj/core/topology.py
mdtraj/formats/pdb/pdbfile.py
tests/test_pdb.py

Adding PDB chainID support

---

mdtraj/core/trajectory.py
mdtraj/formats/__init__.py
mdtraj/formats/pdbx.py
tests/test_pdbx.py

Fixes #652.  This implementation uses OpenMM to do most of the work.

Implement reading and writing PDBx/mmCIF files

---

mdtraj/geometry/order.py

As on tin: this function needed more Math ™️

Sprinkle in some math

---

.github/ISSUE_TEMPLATE.md

Further modifications on issue-template could be added in the future.

Delete notes in issue-template

---

devtools/conda-envs/test.yaml

Tests should pass before making a new release
ref #1789

Pin `gsd=2`

---

devtools/conda-envs/test.yaml
docs/whatsnew.rst

I'm basing this off of the auto-generated blob copied below, which I reformatted to be consistent with the existing style. I'm not married to how the changelog is structured, but I'd rather not try to change it.
```
* Patch util_arm.h for M1 by @sroet in https://github.com/mdtraj/mdtraj/pull/1694
* Avoid side effects in mdtraj.load by @clonker in https://github.com/mdtraj/mdtraj/pull/1706
* [CI] Add python310, add flake to manage nixpkgs version by @rmcgibbo in https://github.com/mdtraj/mdtraj/pull/1711
* Adding PDB chainID support by @pgbarletta in https://github.com/mdtraj/mdtraj/pull/1715
* remove simtk support by @sroet in https://github.com/mdtraj/mdtraj/pull/1698
* Implement reading and writing PDBx/mmCIF files by @peastman in https://github.com/mdtraj/mdtraj/pull/1718
* Update nix …
```

Add v1.9.8 release notes

---

.github/workflows/main.yaml
devtools/conda-envs/test.yaml

Revert "Set up CodeCov"

---

.github/workflows/main.yaml

Adopt SPEC 0 in testing

---

.github/dependabot.yml

The bot should trigger a PR after this ...

Add dependabot for updating actions

---

pyproject.toml
setup.py

https://github.com/mdtraj/mdtraj/issues/1860#issuecomment-2123324794
@jeremyleung521

Add explicit NumPy 1.x pin where `pip`-like tools look

---

setup.py

Adding netCDF4 as a dependency.
Basically this: https://github.com/mdtraj/mdtraj/issues/1897

add netCDF4 as a dependency

---

mdtraj/core/trajectory.py
tests/test_load.py

Allow `mdtraj.load` with `top=None`

---

mdtraj/core/trajectory.py
tests/test_trajectory.py

Sorting atom_indice in atom_slice

---

.github/workflows/main.yaml

Implements #1952
Adding python 3.13 to the testing matrix.

test on python 3.13

---

devtools/conda-envs/test.yaml
docs/requirements.txt
docs/requirements.yaml

This adds openmm as a dep and also sorts the deps (so then future PRs will have a smaller diff)

Run openmm tests on CI

---

docs/conf.py
docs/requirements.txt

I believe we can unpin Sphinx now (#1990) - very minor. The CI should tell confirm if this is true :)

unpin sphinx

---

README.md

How does everyone feel about an update to the project status? I've updated it and added it to the end of the README. There are also some slight adjustments to the header levels in the README
@jeremyleung521 @mattwthompson @sukritsingh

update note on project status

---

mdtraj/core/trajectory.py
mdtraj/formats/pdb/pdbfile.py

Proposed change for issue #2033

Removes header option from pdb writer

---

mdtraj/core/topology.py
tests/test_topology.py

add formal charge in missing places on topology

---

docs/hdf5_format.rst

Fixed typos and did minor reorganization in hdf5 docs

Fixed typos and did minor reorganization in hdf5 docs
