mdtraj/mdtraj

docs/whatsnew.rst
setup.py

Changed 1.2.X to 1.3.0.dev0, which should be more appropriate now that pip has switched to following [PEP440](https://www.python.org/dev/peps/pep-0440/#developmental-releases).

PEP440 version number

---

MDTraj/tests/test_psf.py

Fix for #682 on my machine:
- The VMD in my path is a symlink, so I added a call to `realpath` to resolve that possibility.
- The true VMD location on OSX is `/Applications/VMD 1.9.2.app/Contents/...` which has a space in it, which needs to be escaped for TCL, otherwise it views the space as an argument separator.

Test PSF Fix

---

MDTraj/formats/pdb/data/pdbNames.xml

Added two more CHARMM/NAMD specific aliases for histidine to partially address https://github.com/mdtraj/mdtraj/issues/637. I believe that HSD, HSE and HSP are the standard naming schemes there.

Added additional aliases for HIS

---

mdtraj/core/selection.py
mdtraj/tests/test_selection.py

For #706. Using the following section from the pyparsing docs.
> Word - one or more contiguous characters; construct with a string containing the set of allowed initial characters, and an optional second string of allowed body characters; for instance, a common Word construct is to match a code identifier - in C, a valid identifier must start with an alphabetic character or an underscore ('_'), followed by a body that can also include numeric digits. That is, a, i, MAX_LENGTH, _a1, b_109_, and plan9FromOuterSpace are all valid identifiers; 9b7z, $a, .section, and 0debug are not. To define an identifier using a Word, use either of the following:
- Word( alphas+"_", alphanums+"_" )
- Word( srange("[a-zA-Z_]"), srange("[a-zA-Z0-9_]") )

Allow numbers in literals, but not in 1st character

---

.travis.yml

If you look at https://travis-ci.org/mdtraj/mdtraj/builds, travis hasn't run on a merge commit in the last 19 days. I don't know why. It's been running on PRs, but not on the master branch after the merge commit. This is important for updating the docs.

[TRAVIS] Travis not running on merge commits?

---

mdtraj/rmsd/include/sse_swizzle.h

In order to use this software at Google, we need an OSI license and not public domain so I asked Imran if we could switch the license.
Forwarded conversation
Subject: License for sse_swizzle.h
------------------------
From: Patrick Riley <pfr@google.com>
Date: Thu, Feb 26, 2015 at 1:07 PM
To: Imran Haque <ihaque@cs.stanford.edu>
Imran,
I've been working with Bharath Ramsundar and Steven Kearnes as part of a Stanford-Google collaboration.
I'd like to use mdtraj at Google. mdtraj includes 
sse_swizzle.h
https://github.com/mdtraj/mdtraj/blob/master/mdtraj/rmsd/include/sse_swizzle.h
which you have tried to put into the public domain. 
Google is very careful with its open source licenses and we'd like to have an explicit OSI approved license for this code in order to use it (due to legal …

Switch sse_swizzle to the MIT license after email with Imran

---

mdtraj/geometry/rdf.py

Generating `pairs` scales pretty terribly as the number of atoms increase. This change removes the intermediate list/set creation and uses `fromiter` which is both faster and more memory friendly.

[ENH] Improved efficiency of generating RDF pairs

---

mdtraj/formats/dcd/include/dcdplugin.h
mdtraj/formats/xtc/include/xdrfile_xtc.h
mdtraj/geometry/include/dridkernels.h

* dcdplugin.h and xdrfile_xtc.h: include missing function declarations
* dridkernels.h: include #ifdef'd controlled extern "C" so a C++ compilier can
read the header and successfully link.

Add compilation fixes for extension modules

---

mdtraj/core/topology.py
mdtraj/core/trajectory.py
mdtraj/formats/lammpstrj.py
mdtraj/formats/mol2.py
mdtraj/tests/test_lammpstrj.py

Quick question: there are several docstrings with single quotes lying around with single quotes, e.g.:
https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/topology.py#L947
Is that intentional or just go ahead and fix it if I find em?

Overwrite not being passed to HDF5 and .lammpstrj and some small stuff (doc strings, pep8)

---

mdtraj/geometry/rdf.py

Current code complains when a numpy array is passed instead of a list because the truth value is ambiguous.

Fix compute_rdf r_range argument

---

mdtraj/html/install.py
mdtraj/html/static/widget_imagebutton.js
mdtraj/html/static/widget_trajectory.js

Hi, 
the new version of IPython 3.0 introduced [some changes] (https://github.com/ipython/ipython/wiki/IPython-3.0-comm-and-widget-migration-document) into the widget interface, so that TrajectoryView notebook widget stopped working. This commit seems to fix all of the issues and restores TrajectoryView functionality in the notebook.
Anton.

fix IPython 3.0 compatibility issues

---

mdtraj/formats/netcdf.py

It's supported in Trajectory.save, and it's not like another format has any
kind of claim on that suffix.
Closes #807

Add .ncdf as a recognized suffix for the NetCDF loader

---

mdtraj/formats/gro.py

VMD Doesn't like two spaces before the number of atoms.
It fails with `gromacsplugin) Warning, error reading box, unexpected
end-of-file reached`.

Make vmd-readable .gro

---

docs/api/reporters.rst

`reportInterval` is an argument of `NetCDFReporter`

typo in code example

---

mdtraj/core/trajectory.py
mdtraj/formats/amberrst.py
mdtraj/tests/test_restart.py

This commit adds the ability to write Amber NetCDF and ASCII restart files
automatically based on the .ncrst and .rst7 extensions, respectively.  Since
these are single-frame formats (*only*), single-frame trajectories will write
out the requested file-name while multi-frame trajectories will write out
0-padded filenames with a .# appended (so all #'s have the same width).  e.g.,
with 10 frames, the suffixes will be .01, .02, ... .10 and with 1000 frames, the
suffixes will be .0001, .0002, ..., .1000.

ENH: Recognize .ncrst and .rst7 for trajectory save extensions

---

mdtraj/core/element.py
mdtraj/core/topology.py
mdtraj/formats/arc.py
mdtraj/formats/gro.py
mdtraj/formats/hdf5.py
mdtraj/formats/lh5.py
mdtraj/formats/prmtop.py
mdtraj/formats/psf.py

This aims to make it so no element will raise a `NameError` when a virtual site is present (since that is fairly rare so far).  The goal is to make it just as easy to identify them (`atom.element is elem.virtual` instead of `atom.element is None`) while removing the need to special-case virtually every element inspection for virtual sites before trying to access an attribute of the element.

Make virtual site a new element

---

mdtraj/nmr/__init__.py
mdtraj/nmr/scalar_couplings.py
mdtraj/tests/test_nmr.py

Added a test to leeping's PR #833, and fixed a bug in the docstring where it listed the shape of the return value incorrectly in the scalar coupling functions.

Calculate some more NMR J-couplings

---

mdtraj/formats/amberrst.py
mdtraj/formats/netcdf.py

Time is not required to be present in NetCDF trajectories and it's often the
case that it's not. For example, if trajectories are converted from a format
that does not contain the time (e.g., Amber mdcrd).

Remove warnings when NetCDF files do not have time information

---

mdtraj/geometry/dssp.py
mdtraj/geometry/hbond.py
mdtraj/geometry/tests/test_dssp.py

This changes `compute_dssp` to label residues that are not legit protein residues with a different code ('NA' for "not applicable") instead of 'C'.
Relevant addition to docstring: "A special 'NA' code will be assigned to each 'residue' in the topology which isn't actually a protein residue (does not contain atoms with the names 'CA', 'N', 'C', 'O'), such as water molecules that are listed as 'residue's in the topology."
addressed #803
@cing: what do you think of this solution?

ENH: Add NA code to dssp for non-protein residues

---

mdtraj/formats/pdb/pdbfile.py
mdtraj/formats/xyzfile.py
mdtraj/io.py
mdtraj/tests/test_io.py
mdtraj/tests/test_zipped.py
mdtraj/utils/__init__.py
mdtraj/utils/zipped.py

Pytables (`import tables`) has been an optional dependency of MDTraj for a while. It's used by HDF5TrajectoryFile, and by `mdtraj.io`. We accidentally made it a required dependency by adding the function `open_maybe_zipped` to `mdtraj.io`, and then importing `open_maybe_zipped` from inside the PDB code which is imported at startup, causing a user's `import mdtraj` to fail if they don't have pytables.
This is issue #852.
PR fixes the issue by moving `open_maybe_zipped` to a new file inside `utils`, and adding a comment to `io.py` that explains what's going on.
This looks like a kind of annoying bug for packages that depend on MDTraj and use Travis-CI (like https://github.com/markovmodel/PyEMMA/pull/349 and https://github.com/choderalab/openmoltools/pull/123), so I think we should do a …

BUGFIX: Fix pytables inadvertently being moved to a required dependency

---

mdtraj/formats/lammpstrj.py

This should hopefully fix two issues:
* ensure that coordinates of different styles don't get mixed if multiple styles are present
* ensure the predictability of the style of coordinate that gets read in from a file with multiple styles
@swails does this look like a decent solution to what we talked about in #858?

Lammpstrj column ordering fixes

---

mdtraj/core/trajectory.py
mdtraj/tests/test_trajectory.py

added a skip keyword to generate time lagged iterators. Currently the NetCDF loader complains about this new keyword, but I dont know how to fix this properly.

[iterload] added skip keyword to skip first n frames.

---

basesetup.py
setup.py

* NumPy includes and Cython extensions are handled transparently.
* Requires setuptools >= 18
closes #933

Automized setup (pip) to drag-in build time dependencies (numpy, cython)

---

mdtraj/formats/netcdf.py
mdtraj/tests/test_netcdf.py

`cpptraj` was refusing to read mdtraj-generated `.nc` files because we weren't following the spec to a T (or an "xyz")
This fixes it and adds a test. The test requires cpptraj. Should we skip on travis and how?

Follow the Amber NetCDF Trajectory Spec (for compatibility with cpptraj)

---

basesetup.py

`python setup.py develop` was not compatible with some of the distutils hacks in basesetup. fixed.

Fix setup.py develop with latest version of setuptools

---

basesetup.py

Without this change, one can not use python setup.py develop:
``` python
File "setup.py", line 228, in <module>
'mdinspect = mdtraj.scripts.mdinspect:entry_point']},
File "/home/marscher/anaconda/lib/python2.7/distutils/core.py", line 151, in setup
dist.run_commands()
File "/home/marscher/anaconda/lib/python2.7/distutils/dist.py", line 953, in run_commands
self.run_command(cmd)
File "/home/marscher/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "/home/marscher/anaconda/lib/python2.7/site-packages/setuptools/command/develop.py", line 32, in run
self.install_for_development()
File "/home/marscher/anaconda/lib/python2.7/site-packages/setuptools/command/develop.py", line 117, in install_for_development …
```

[setup] do not call parent function via super, because Extension is an old-style class.

---

mdtraj/geometry/rdf.py

This changes how the numpy histogram is invoked so that it uses the new optimizations from https://github.com/numpy/numpy/pull/6100 and as discussed in #734.

Use improved numpy histogram in RDF.

---

setup.py

This leads to the following error message (eg. with setuptools==17 installed):
``` python
$ python setup.py build_ext
File "setup.py", line 17, in <module>
import pkg_resources
File "/home/marscher/miniconda/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/pkg_resources/__init__.py", line 3074, in <module>
File "/home/marscher/miniconda/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/pkg_resources/__init__.py", line 3060, in _call_aside
File "/home/marscher/miniconda/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/pkg_resources/__init__.py", line 3087, in _initialize_master_working_set
File "/home/marscher/miniconda/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/pkg_resources/__init__.py", line 647, in _build_master
File …
```

[setup] require at least setuptools>=18 before doing anything.

---

basesetup.py
setup.py

Fixes #984. I really wish there were a way to have this feature work robustly, but unfortunately I don't think we're quite there yet.
Without numpy/cython installed, you will now get the following error message on installation.
```
$ pip install .               
Processing /home/rmcgibbo/projects/mdtraj
Complete output from command python setup.py egg_info:
--------------------------------------------------------------------------------
Error: building mdtraj requires numpy and cython>=0.19
Try running the command ``pip install numpy cython`` or
``conda install numpy cython``.
or see http://docs.scipy.org/doc/numpy/user/install.html and
http://cython.org/ for more information.
If you're feeling lost, we recommend downloading the (free) Anaconda python
distribution …
```

Revert setup.py clever handling of numpy and cython

---

mdtraj/geometry/contact.py

In compute_contacts right after the call into compute_contacts, there is some inefficiency due to the usage of a python list for n_atoms_per_residue_pair.
See markovmodel/pyemma#448
Converting the list to an array greatly improved the runtime from 60s to 20s for the same data set.

[contact] convert list to array greatly improves performance

---

devtools/conda-recipe/meta.yaml
mdtraj/core/topology.py
mdtraj/tests/test_topology.py

This adds a more efficient pathway to unique pair generation when `a_indices` and `b_indices` are mutually exclusive. It might be time to role some cython code at this point though...
Also anyone have any better naming suggestions for the 3 methods?

Improve speed/efficiency of 1 case of top.select_pairs

---

examples/clustering.ipynb

One has to convert a redundant matrix to a condensed form for it to work with scipy.cluster.hierarchy.linkage(). See also: https://github.com/scipy/scipy/issues/5508

redundant matrices don't work in scipy.cluster

---

mdtraj/core/selection.py
mdtraj/core/topology.py
mdtraj/formats/hdf5.py
mdtraj/formats/pdb/pdbfile.py
mdtraj/formats/pdb/pdbstructure.py
mdtraj/formats/pdb/tests/test_pdb.py
mdtraj/formats/psf.py
mdtraj/tests/test_psf.py
mdtraj/tests/test_topology.py

Both psf and pdb topology readers get a segment_id from files, but this is not stored anywhere. This is an extremely useful way to do selections for systems with complex topology (vs chains, which are numbered).
Segment_id is now elevated to a main, although not required, property of the residue class. 
Segment_id is read from psf and pdb file readers and stored in this attribute. It has also been added to the data frame object list of columns (which could be a problem if anyone is storing topologies as data frames for future use). 
Segment_id or segname (vmd style) can be used in atom selections.
save_pdb has been adjusted to write out segment_id in the proper style. 
I believe I have also successfully added segment_id to the topology information in hdf5 writing without breaking …

add segment_id as residue attribute

---

.gitignore
basesetup.py
mdtraj/formats/binpos/src/binposplugin.c
mdtraj/geometry/drid.pyx
mdtraj/geometry/include/dridkernels.h
mdtraj/geometry/src/dridkernels.c
mdtraj/geometry/src/moments.c
mdtraj/rmsd/_rmsd.pyx
mdtraj/rmsd/src/Munkres.cpp
setup.py

Small cleanup

---

.gitignore
mdtraj/__init__.py
mdtraj/testing/nosetester.py
mdtraj/tests/test_psf.py
runtests.py

@brookehus this may make running the tests a little more straightforward. I was trying to figure out a way to avoid needing to run `python setup.py develop` before running the tests to avoid having the imports not work, but couldn't figure anything out. I copied this from numpy, which uses the same scheme.
The basic workflow should just be
```
$ python runtests.py
```
or to run just a specific test 
```
$ python runtest.py -t mdtraj/tests/test_trajectory.py:test_load
```

Add new test runner for development

---

mdtraj/formats/gro.py

When you extract a GRO file using ```trjconv``` it often auto generates a comment for the top of the file that includes the text t= framenum. In my workflow, I extract frames and then resolvate the target protein. The gromacs tool ```solvate``` then adds "in water" to the end of the comment string. 
This results in the following auto-generated GRO file, where the comment includes text after the numeric timestep value.
```
Protein t= 3000.00000 in water
13
2ALA      N    1   7.293   1.835   0.876 -0.6990 -0.1367  0.0623
2ALA    HT1    2   7.295   1.777   0.794 -0.8018 -0.1406  0.0630
2ALA    HT2    3   7.249   1.836   0.966 -0.7856 -0.0003  0.0192
2ALA     CA    4   7.379   1.951   0.859 -0.3148 -0.4056  0.1486
2ALA     HA    5   7.423   1.943   0.761 -0.2301 -0.6462  0.2067
2ALA   MCB1 …
```

Generalized gro file parsing of file comment

---

appveyor.yml
mdtraj/formats/xtc/include/ms_stdint.h
mdtraj/formats/xtc/include/trr_header.h
mdtraj/formats/xtc/include/xdr_seek.h
mdtraj/formats/xtc/include/xdrfile.h
mdtraj/formats/xtc/include/xdrfile_trr.h
mdtraj/formats/xtc/src/README
mdtraj/formats/xtc/src/xdr_seek.c
mdtraj/formats/xtc/src/xdrfile_trr.c
mdtraj/formats/xtc/trr.pyx
mdtraj/formats/xtc/trrlib.pxd
mdtraj/formats/xtc/xdrlib.pxd
mdtraj/formats/xtc/xtc.pyx
mdtraj/tests/test_trr.py
mdtraj/tests/test_xtc.py
setup.py

This method will read an integer per frame to determine the byte offsets between
frames for XTC files. TRR files on the other hand store the sizes of a frame in
a private data structure in xdrlib (which has been exposed to handle this).
For small XTC files (<= 9 atoms), the coordinates are written uncompressed,
which is reflected in the offset calculation.
Note that the amount of bytes needed for frames can be figured out by reading
the original source code of xdrlib (GROMACS).
The byte offset array will only be constructed if requested by the user,if he/she
wants to know the lengths of the trajectory or he/she demands random access
(seeking). The offsets are accessible via a property of the
XTC|TRRTrajectoryFile and cached (stored to disk and restored via the setter).

[xtc|trr] added seek support to provide fast random access.

---

examples/clustering.ipynb

The introduction of squareform (cc #997)  didn't work because of small off-diagonals
scipy's ward complains when the original observations aren't present, so I changed it to average linkage
addresses #1049

Fix clustering example

---

mdtraj/formats/pdb/pdbfile.py
mdtraj/tests/test_trajectory.py

standard_names = False will keep all atom names and residue names intact, even if these are not standard. Addresses #1016

[load_pdb] new optional argument standard_names

---

mdtraj/formats/xtc/xtc.pyx
mdtraj/tests/test_xtc.py

Fixes #1078. For short trajs there is a rounding error (forced cast
to integer) to the next smallest integral. Passed new_size to ceil.

[xtc] fix a bug in calc of offsets array for short trajs.

---

mdtraj/formats/xtc/xtc.pyx

I consider this a minor issue, since the program crashes in this case any ways. Now it prints a proper message instead of "String format error".

[xtc] fix error status report during xdr_seek

---

.travis.yml

The `os: linux` condition in the deploy section wasn't doing anything and it was deploying on one of  the macosx builds and one of the linux builds. In practice, this didn't make a difference because the generated docs should be more-or-less identical.

Update travis.yml to really only deploy once

---

docs/examples/introduction.rst

In one line, a list was called "atom_to_keep", in another, it was referred to as "atoms_to_keep"

Fixed typo in introduction

---

mdtraj/geometry/hbond.py

Hi MDTraj team,
Here are some changes I've made to the hbond-finding functions to make them run about six times faster, as well as adding the option sidechain_only, to consider only sidechain-sidechain interactions. I still have to write a test for the code, but in my ad-hoc testing all outputs have been identical to previous versions of mdtraj, just faster. Feel free to integrate this code however you like.
Note: I also haven't added documentation for the sidechain_only option, which should be done if it's something you want to support.
Thanks,
Connor

Optimize baker_hubbard and wernet_nilsson functions

---

mdtraj/formats/xtc/xtc.pyx
mdtraj/tests/test_xtc.py

This is the standard exception in mdtraj being raised for invalid seek operations.
Before this change, one will get an IndexError (thrown by numpy), which could be confusing.

[formats/XTC] in case of an out of bounds seek, raise IOError

---

mdtraj/geometry/tests/test_drid.py

in favor of numpy.nanmean
http://docs.scipy.org/doc/scipy-0.17.0/reference/generated/scipy.stats.nanmean.html
Seems to be API compatible.

scipy.stats.nanmean deprecated

---

mdtraj/geometry/src/neighborlist.cpp

I got segfaults when using a large cutoff radius on a relatively small unit cell. This is a corner cases that is probably rarely met in practice but it should still be fixed.

There should never be zero bins in Voxels class

---

mdtraj/core/trajectory.py
mdtraj/tests/test_load.py

I just got bit by this issue, and I want to make sure others don't run into it.
The `load` function can handle either a single filename or a list of filenames. When dealing with a list of filenames, it loads each trajectory and then joins them together sequentially. This joining process creates copies of the coordinate data.
When passing a one-element list containing only one filepath, `load` attempts to `join` the single loaded trajectory with an empty list (generated from a slice at trajectory.py:96), triggering a copy of the trajectory's coordinate data. Because of this, I was consistently running out of memory when trying to load a particularly large trajectory.
This pull request modifies `load` to "peel" single-element lists, so that they are treated as if the element were passed as …

Load single-element path lists without a copy

---

mdtraj/formats/prmtop.py
mdtraj/formats/psf.py

When loading a trajectory with a psf topology and using the stride or atom_indices arguments, the following error message would be produced:
```
a=md.load('test.nc', top='test.psf', stride=10)
File "<stdin>", line 1, in <module>
File "/opt/anaconda/lib/python2.7/site-packages/mdtraj-1.8.0.dev0-py2.7-linux-x86_64.egg/mdtraj/core/trajectory.py", line 372, in load
kwargs["top"] = _parse_topology(kwargs["top"], **topkwargs)
File "/opt/anaconda/lib/python2.7/site-packages/mdtraj-1.8.0.dev0-py2.7-linux-x86_64.egg/mdtraj/core/trajectory.py", line 174, in _parse_topology
topology = load_psf(top, **kwargs)
TypeError: load_psf() got an unexpected keyword argument 'stride'
```
This is from a bug introduced in 68d6232d9e5f421a695dadf689cad3d0bd1655a2 where keyword …

Handle unexpected keyword arguments gracefully in psf and prmtop parsers

---

mdtraj/rmsd/_rmsd.pyx

Per discussion in #1189, added a warning to rmsd when `precentered=True` but `atom_indices != None` causing `precentered` to be ignored. @rmcgibbo

Add warning to rmsd() if precentered == True and atom_indices != None

---

mdtraj/formats/amberrst.py

Got this message from pmemd:
> Warning: In netcdf file, expected picosecond for attribute units, got picoseconds

Amber restart file convention

---

mdtraj/core/trajectory.py
mdtraj/tests/test_trajectory.py

Both bugs occur for topology formats that can also be trajectories
because MDTraj attempts to apply the args twice. When passing `frame`,
it's simply the `TypeError` reported in #1226. When it's `atom_indices`,
the topology gets sliced once when loading the topology and then again
when loading the trajectory. This does not cause any problems when
slicing from 0:n but fails when slicing indices past that.
Resolves #1226
cc @mattwthompson who found the `atom_indices` issue

Fix bugs in load with atom_indices and frame args

---

mdtraj/formats/mol2.py
mdtraj/testing/reference/li.mol2
mdtraj/tests/test_mol2.py

Currently, reading in a mol2 without bonds fails when it tries to renumber the bonds to 0 index:
```
import mdtraj as md
md.load('li.mol2')
```
with mol2 file:
```
@<TRIPOS>MOLECULE
RES
1 0 1 0 1 
SMALL
NO_CHARGES
@<TRIPOS>CRYSIN
10.0000    10.0000    10.0000    90.0000    90.0000    90.0000  1  1
@<TRIPOS>ATOM
1 Li           0.0000     0.0000     0.0000 opls_404      1 RES    
@<TRIPOS>BOND
@<TRIPOS>SUBSTRUCTURE
1 RES             1 RESIDUE    0 **** ROOT      0 
```
> Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "//anaconda/lib/python3.5/site-packages/mdtraj/core/trajectory.py", line 428, in load
value = loader(filename, **kwargs)
File "//anaconda/lib/python3.5/site-packages/mdtraj/formats/mol2.py", line 108, in load_mol2
offset = bonds_mdtraj.min()  # …

Skip renumbering if no bonds in mol2

---

docs/whatsnew.rst
mdtraj/geometry/alignment.py
mdtraj/geometry/tests/test_alignment.py

Currently, if you create a transform object with `compute_transformation`,
you will get a Transform object that will only be able to correctly
transform groups of atoms that are the same as the target, i.e. you currently
can't align an entire system including water when you just compute
the transformation matrix on protein.
Perhaps there was a reason why it was written this way, but it currently does not deliver the behavior I was expecting. This fix should be more general and what users expect. I will come up with some tests and will commit them also.

 Fix tranform calculation and Transform object to be more general.

---

mdtraj/formats/pdb/data/pdbNames.xml

Fix #1256: Add O1 as alternative definition for water oxygen.

---

.gitignore

mdtraj/formats/tng/lib matches this, but it shouldn't be ignored.
Luckily it was checked in anyways :)

Remove "lib" from .gitignore

---

mdtraj/rmsd/src/center.c

Per #1281, when `n_frames * n_atoms * 3` is greater than the maximum size of a signed 32-bit integer, an overflow error causes a segmentation fault in `mdtraj/rmsd/src/center.c`.
This PR fixes this by converting the offending `int` to a ~`size_t`~ `long long`.

Fix precentering overflow error in center.c

---

basesetup.py

Fixes the buggy code that adds the include path of numpy headers to the c compiler.
This pull request does two jobs:
1) Clears the buggy code in basesetup.py (the useless initialize_options() override)
2) Add a common and reliable mechanism that finds the numpy include path and plumbs
the path to the Extension objects.
This pull request affects:
1) Building mdtraj with pip/from source.
Rationales:
1) the build_ext class is ultimately subclassing the distutils.command.build_ext. See [setuptools.command.build_ext, line 5](https://github.com/pypa/setuptools/blob/aa41a7a58d0e1cd0dd6715b2d4057666410114c7/setuptools/command/build_ext.py#L5) and [cython.Distutils.build_ext, line 5](https://github.com/cython/cython/blob/ef241f5bc514075aea713d0e93aad3239df253b4/Cython/Distutils/build_ext.py#L5). …

Fix the build bug caused by incorrect plumbing the `numpy include path` into the cflags

---

mdtraj/geometry/rdf.py

The RDF function used to compute pairs based on input but this was factored out to separate functions. It is now a required argument for `compute_rdf` but I never updated it here.
Thanks to @deadpriest88 for catching this.

Make RDF `pairs` argument required

---

README.md

I think this is broken. It reports 0/mo (which doesn't look good anyway). But also the shields.io example for django also reports 0/mo which doesn't seem right :)

Remove PyPI downloads badge

---

.travis.yml
devtools/conda-recipe/meta.yaml
mdtraj/__init__.py
mdtraj/core/topology.py
mdtraj/formats/mol2.py
mdtraj/utils/singleton.py
tests/test_mol2.py
tests/test_pdb.py
tests/test_tng.py
tests/test_topology.py

This PR ports the [OpenMM bond order](https://github.com/pandegroup/openmm/pull/1668) representation into MDTraj. Implements the `Bond` class to Topology and updates the Mol2 reader to use bond_order field.
This does change the API a bit since bonds are now represented by a class instead of just two atoms. However, most backwards compatibility should be preserved as each `Bond` is subclass of the `namedtuple` so you can iterate by `for a,b in top.bonds` and still get a `Atom` class for `a` and `b`. This behavior is only different in the `to_dataframe` output (see below).
There are a couple of points which I implemented which I would like some additional feedback on.
1. Equality/Less than/Greater than of a Bond: Right now I only compare Atom index and not Type/Order since defining these …

Add Bond Order information to Topology

---

devtools/conda-recipe/meta.yaml
examples/test_examples.py

The reason for #1314 seems like a timeout from something being very slow to load. I marked it as flaky. Using pytest-ignore-flaky (https://github.com/conda-forge/staged-recipes/pull/4513), we could make that an xfail.

Mark centroids.ipynb as flaky

---

mdtraj/formats/xtc/xtc.pyx
tests/test_xtc.py

This should avoid a lot of IO for high stride arguments,
because unwanted frames are just seeked over.
This feature relies on the byte offsets, which have to be provided
or explicitly computed by accessing the offsets property once.
If no bytes offset is available, the current behaviour is untouched.
Added tests.

[formats/xtc] use byte offsets between frames for stride if avail

---

mdtraj/formats/xtc/trr.pyx
mdtraj/formats/xtc/xtc.pyx
tests/test_trr.py
tests/test_xtc.py

This also changes how many frames will be returned when using the stride. Eg. if one requests 100 frames with stride 2, one will also get 100 frames offset by 2 steps. This is at least what the docstring said, but was not true until this change.

[TRR] added efficient stride handling

---

setup.py

Adding OpenMP compiler flags to the geometry extension, fixes #1335.
Should this also be done for `format_extensions`? If you grep many of the `.c` files built by cython, there is an `#ifdef _OPENMP`/`#endif` block, but I don't see where parallelism is actually used... maybe someone more familiar with that code could comment? (@Lnaden @mpharrigan @marscher)

Compile geometry extension with OpenMP.

---

mdtraj/geometry/neighborlist.pyx

This is essentially the same as #1146, but that only changed `compute_neighbors`. This provides the same fix for `compute_neighborlist`.
(For search results) The error we'd been getting was:
```pytb
File "mdtraj/geometry/neighborlist.pyx", line 76, in mdtraj.geometry.neighborlist.compute_neighborlist (mdtraj/geometry/neighborlist.cpp:1943)
ValueError: Buffer dtype mismatch, expected 'float' but got 'double'
```
CC: @Nicole-de-groot

Ensure correct dtype in neighborlist box vectors

---

mdtraj/formats/dcd/dcd.pyx
tests/test_dcd.py

This yields almost the same frames a it used to,
but at the end of the trajectory there were some
frames missing in the current impl.
In PyEMMA we rely upon mdtraj is handling the
stride like numpy.
Added hints on howto improve the reader further
(efficient seeking by byte offset)

[formats/dcd] handle stride like numpy

---

mdtraj/core/trajectory.py

The .prm7 topology file extension appears to be widely used as an alternative to .parm7 within the AMBER community. I've added support for this.

Added support for prm7 topology file extension.

---

devtools/travis-ci/build_docs.sh
docs/requirements.txt
docs/sphinxext/notebook_sphinxext.py
mdtraj/formats/xtc/trr.pyx
mdtraj/formats/xtc/xtc.pyx
tests/test_trr.py
tests/test_xtc.py

My previous patch in #1331 and #1332 borked chunked operations with stride > 1, because the desired frames were being calculated from the last frame_counter. This leads to problems when reading with a chunksize. Luckily we have not released this yet.
Now the stride handling is performed either by dummy reads or efficiently by seeking over the skipped frames. This yields the same frame indices like numpy.arange(0, traj_len, stride).
I promise I am certain now about these changes, because we are wrapping up very detailed reader tests in PyEMMA and everything is working as expected with this patch. The existing mdtraj tests pass as well (locally).

[XTC|TRR] striding relative to current position + build_docs fix

---

mdtraj/formats/mol2.py
tests/test_mol2.py

In reference to #1379, `bond_value` is converted to a string which allows all mol2 files to be loaded in properly.
`test_load_all_mol2` unit test was added to ensure that every mol2 file in the `data` directory is properly loaded.

Ensure 'bond_value' is a string

---

mdtraj/formats/mol2.py
tests/data/cl.mol2
tests/data/li.mol2
tests/test_mol2.py

I attempted to load a mol2 file containing Ti atoms using MDTraj, I would get the error: `KeyError: 'T'`.  After doing some digging in `mol2.py`, I found that the reason for this is because of the following line: `atoms_mdtraj["element"] = atoms.atype.apply(lambda x: x.strip(".")[0])`.  Because strip() returns a string, this line returns the first letter of a two letter element symbol.
As a result, I think split() is a more appropriate method in this case since it returns a list.  For example, `'Ti'.split('.')` will return `['Ti', '']` and `'Ti'.split('.')[0]` will return `'Ti'` which is the desired result.
In addition to this change, I added a unit test to `test_mol2.py`.  By loading in `cl.mol2`, this test ensures that the correct element name is loaded in.

Replace strip() with split() in `mol2.py`

---

mdtraj/__init__.py

by importing numpy before loading cython extensions,
because numpy inserts a proper warning filter
Fixes #1390

silence cython related numpy warnings

---

examples/principal-components.ipynb
examples/ramachandran-plot.ipynb
examples/rmsd-drift.ipynb
examples/solvent-accessible-surface-area.ipynb

A few tests are failing because recent versions of Jupyter strictly enfore the rule that `from __future__` imports must be the first line in a cell (see, for example, the Py-3.6 test [here](https://travis-ci.org/mdtraj/mdtraj/jobs/454545185#L3469)). These notebooks had cells like:
```python
%matplotlib inline
from __future__ import print_function
```
This PR just switches the order of those first two.

Notebook tests: `from __future__` must come first

---

appveyor.yml
devtools/conda-recipe/meta.yaml
examples/test_examples.py
mdtraj/formats/mol2.py

In DataFrame.atype.apply we get a list for Python2, but a
str for Python3 - so we need to distinguish this.
Moreover we need to check for orbital hybridization ($E.sp_x)
and 'weird' element names, which are not specified in SYBL nor GAFF,
e.g. CT, OS, CK etc.
The latter is ensured via trying to parse the element first with its
two letter code (Li etc.), if that fails, fall back to a one letter
code. This succeeds at least for the provided test examples.
Fixes #1387

[formats/mol2] add more checks to element parsing

---

mdtraj/geometry/src/image_molecules.pxi

Trying to run `trajectory.make_molecules_whole()` on a medium-sized trajectory (101k atoms) on Windows 10 (64-bit) gives the following error:
```In [3]: t.make_molecules_whole()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-cf06762aa5a9> in <module>
----> 1 t.make_molecules_whole()
~\Miniconda3\envs\py36\lib\site-packages\mdtraj-1.9.3-py3.6-win-amd64.egg\mdtraj\core\trajectory.py in make_molecules_whole(self, inplace, sorted_bonds)
1901         box = np.asarray(result.unitcell_vectors, order='c')
1902         print(result.xyz.shape, box.shape, len(sorted_bonds), max(map(len, sorted_bonds)))
-> 1903         _geometry.whole_molecules(result.xyz, box, sorted_bonds)
1904 …
```

Fixes 'Buffer dtype mismatch' error on 64-bit Windows

---

devtools/conda-recipe/meta.yaml

It seems to kill these py2k linux jobs with an md5 mismatch https://travis-ci.org/mdtraj/mdtraj/jobs/478463660

Disable downloading shiftx2 for now

---

mdtraj/formats/mol2.py

In #1407 an little function was added to try and more intelligently parse the various atomtypes that can be included in a mol2 file. However, it can hit an infinite loop if the string and its first element each do not constitute an element. Currently trying to parse a bad element, i.e. `'L'` will cause a recursion error from repeatedly calling itself and hitting the key error, whereas this change will cause it to simply fail out with a key error without hitting the recursion limit. This shouldn't affect any existing behavior since the other checks in the function already happened.
cc @marscher

Avoid infinite recursion error in mol2 parser

---

mdtraj/reporters/basereporter.py

Addresses #1429 : `Reporter` classes no longer override user request to write unit cell information if `Topology` is missing unit cell information.

Reporters no longer override user request to write unit cell information

---

mdtraj/geometry/__init__.py
mdtraj/geometry/distance.py
tests/test_geometry.py

Seems to be low-hanging fruit, sometimes we deal with non-element "sites," i.e. coarse-grained beads. In my case I happen to be using LAMMPS files for which reading masses is cumbersome and a center of geometry is good enough.

Add compute_center_of_geometry

---

mdtraj/core/trajectory.py

Fixes "ValueError: Buffer dtype mismatch, expected 'int32_t'" but got 'long' in mdtraj.geometry._geometry.image_frame.

add missing type conversion in image_molecules before calling C code

---

docs/analysis.rst
mdtraj/geometry/__init__.py
mdtraj/geometry/order.py
tests/test_order.py

Easy access to the gyration tensor has a number of useful properties related to [calculating a number of shape metrics of a system](https://isg.nist.gov/deepzoomweb/measurement3Ddata_help). With access to the gyration tensor calculation of the principal moments, axis, asphericity, acylindricity, and relative shape anisotropy can all be computed relatively easily.
This pull request adds `compute_gyration_tensor` to geometry/order.py with associated unit tests in `test_order.py` in much of the same style as `compute_inertial_tensor` is currently implemented. Calculations of the shape descriptions listed above can also be implemented, if you would like.
1. [x] Added `compute_gyration_tensor` and `_compute_gyration_tensor_slow` to `geometry/order.py`
2. [x] Added unit test to `test_order.py`

Add gyration tensor calculation

---

mdtraj/rmsd/src/center.c

hopefully closes #1475.
Following [this guide](https://www.gnu.org/software/gcc/gcc-9/porting_to.html), it has an example for `OpenMP data sharing`:
```c
int get (void);
void use (int);
void foo (void) {
const int a = get ();
const int b = 1;
#pragma omp parallel for default(none)
for (int i = 0; i < a; i += b)
;
// The above used to compile with GCC 8 and older, but will
// not anymore with GCC 9.  firstprivate(a, b) clause needs
// to be added for C, for C++ it could be just firstprivate(a)
// to make it compatible with all GCC releases.
}
const int huge_array[1024] = { ... };
void bar (void) {
#pragma omp parallel for default(none)
for (int i = 0; i < 1024; i++)
use (huge_array[i]);
// Similarly, this used to compile with GCC 8 and older and
// will not anymore.  Adding …
```

Fix pip install?

---

devtools/conda-recipe/meta.yaml
mdtraj/formats/xtc/src/xdrfile_trr.c
tests/test_trr.py

Fixes #1481 (at least, once it is done I hope it will).
I'll also check a few other file formats (at least XTC) to see if this repeats elsewhere before calling it ready.
@rmcgibbo : For the moment, I added `psutil` to the testing requirements in the conda recipe (test requires it), but also allowed it to skip with a `pytest.importerskip` if `psutil` isn't available. Other options would be to not include `psutil` in the test reqs and skip it, or to not allow it to be skipped. Let me know if you'd prefer a different approach.

Fix `read_trr_natoms` leaving malformed file open

---

basesetup.py

Might fix #1487. @justinrporter: would you be able to test if this works?

Fix _detect_openmp possibly

---

docs/analysis.rst
mdtraj/geometry/__init__.py
mdtraj/geometry/order.py
mdtraj/geometry/shape.py
tests/test_order.py
tests/test_shape.py

Extension of #1467. Functions for computing a number of shape metrics using the gyration tensor are added. 
All the new functionality is built in the newly created module `geometry/shape.py`, with associated tests in `tests/test_shape.py`. 
References:
https://isg.nist.gov/deepzoomweb/measurement3Ddata_help
https://en.wikipedia.org/wiki/Gyration_tensor

Add calculations for shape metrics

---

mdtraj/formats/pdb/pdbfile.py

According to the [PDB file specifications](https://www.wwpdb.org/documentation/file-format-content/format33/sect9.html), the atom symbol should be right-justified in columns 77 and 78 of each ATOM/HETATM entry. Although most visualization programs handle left-justified atom symbols, several crystallographic packages throw errors when the atom symbol is left-justified.
This pull request changes the output from `PDBTrajectoryFile.write()` to adhere to the right-justified specification.
Namely, it changes this format string:
`line = "ATOM  %5d %-4s %3s %1s%4d    %s%s%s  1.00 %5s      %-4s%-2s  "`
to this:
`line = "ATOM  %5d %-4s %3s %1s%4d    %s%s%s  1.00 %5s      %-4s%2s  "`

Right-justify atom symbol when writing PDB files

---

mdtraj/geometry/drid.pyx

As written, DRID calculations were not thread parallelized. Most of the work had already been done to do this, however, since each atom's DRID can be calculated in parallel, and dispatch to the `drid_moments` function is independent by atom.
This PR just adds openmp parallelization of the inner loop of the DRID calculation.

Thread parallelism for DRID

---

mdtraj/geometry/distance.py

This makes `mdtraj.compute_displacements` behave similar to  `compute_distances` when provided with an empty slice as `atom_pairs` (returning an empty slice as well)
current code returns a crytpic error:
```python
>>> import mdtraj as md
>>> import numpy as np
>>> traj = md.load('test.xtc', top='test.pdb')
>>> c = np.array([[3000, -1]])
>>> d = c[0:0]
>>> d
array([], shape=(0, 2), dtype=int64)
>>> md.compute_distances(traj, d) # Expected behaviour
array([], shape=(101, 0), dtype=float32)
>>> md.compute_displacements(traj, d)
File "<stdin>", line 1, in <module>
File "/home/sroet/miniconda3/envs/dask-traj/lib/python3.7/site-packages/mdtraj/geometry/distance.py", line 123, in compute_displacements
_geometry._dist_mic_displacement(xyz, pairs, …
```

let compute_displacements handle empty atom_pairs

---

mdtraj/geometry/hbond.py

Check that topology.bonds has a length greater than zero in the "_get_bond_triplets" function; otherwise, raise an error. Having a topology.bonds list is necessary to run the  hydrogen bond commands: baker_hubbard and wernet_nilsson; however, no explicit error message is given and an empty list is returned after running the aforementioned functions. This added check isn't robust as it only checks to see if there is at least one bond in topology.bonds, ... but it gets the job done!

ValueError Addition : Check topology.bonds > 0

---

mdtraj/formats/gro.py

Not sure if this will work as intended, but I added one line to automatically create the standard bonds list. This is necessary for other commands such as the hydrogen bonding wernet_nilsson() or baker_hubbard() functions. Without this change, an empty list would be returned upon using those functions.

Minor addition: create standard bonds

---

mdtraj/core/selection.py

Just seeing if the proposal in https://github.com/mdtraj/mdtraj/issues/1509 passes CI. This passes locally this locally in a 3.7 environment, which is encouraging.

Add posonlyargs argument for Python 3.8 compatibility

---

basesetup.py

Without the header there is only an implicit declaration warning, but I doubt it was doing what we were expecting.

[basesetup] pass omp.h header in OpenMP detection

---

mdtraj/formats/xtc/trr.pyx

Fixed declaration of frame_offset that lead to offsets wrap at 2.1E9 when loading large trajectories

TRRTrajectoryFile offset fix (mdtraj#1533)

---

devtools/conda-recipe/meta.yaml
mdtraj/core/selection.py
setup.py
tests/test_selection.py

Astor doesn't appear to work with python38, and astuparse is a superior/maintained version of the same thing.
Required for #1520

Replace astor with astunparse for selection ast manipulations

---

devtools/azure-pipelines-win.yml

Windows CI is currently failing with
```
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... failed
ERROR conda.core.link:_execute(568): An error occurred while installing package 'conda-forge::pkginfo-1.5.0.1-py_0'.
CondaError: Cannot link a source that does not exist. C:\Miniconda\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.
Attempting to roll back.
Rolling back transaction: ...working... done
CondaError: Cannot link a source that does not exist. C:\Miniconda\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.
```
(https://dev.azure.com/rmcgibbo/mdtraj/_build/results?buildId=196&view=logs&j=c3584bed-92ea-506a-4dd3-f90b4f6e31cb&t=2138432d-6752-57c8-2564-add6273e64b …

Attempt to fix windows CI

---

mdtraj/formats/xtc/xtc.pyx

When n_frames is guessed from the xtc file size, we should take into account the stride when estimating how many frames we're going to read (used to malloc buffer sizes).
@danijoo, could you see if this fixes your test case?

Possible fix for #1458

---

devtools/azure-pipelines-linux.yml
devtools/conda-recipe/meta.yaml

We generally support the 2 most recently released minor versions of python, so this drops testing of 3.6 and adds 3.8. If it works I'll expand the PR to the other OSes.

Update azure-pipelines-linux to python 3.8

---

mdtraj/core/trajectory.py
mdtraj/utils/validation.py

I am getting some `DeprecationWarning`s in some package that I manage, that bubble up from mdtraj.
Like:
```
~/miniconda3/envs/test/lib/python3.8/site-packages/mdtraj/core/trajectory.py:32: 
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
from collections import Iterable
```
Apparently the [Abstract Base Classes](https://docs.python.org/3.8/library/collections.abc.html#collections-abstract-base-classes) have been moved to `collections.abc` since python `3.3`. mdtraj uses the ABCs `Iterable` and `Sequence`.
This PR fixes that deprecation warning.

fix collections.abc deprecation warnings

---

mdtraj/rmsd/_rmsd.pyx
tests/test_rmsd.py

As I understand, `atom_indices` are indices of atoms in the `target`, and `ref_atom_indices` are indices in the `reference`.
However [here](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/rmsd/_rmsd.pyx#L138) `atom_indices` are compared to the `reference` size, but they shouldn't be since they index atoms in a different trajectory (topology).
The same applies [here](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/rmsd/_rmsd.pyx#L151) where `ref_atom_indices` are compared to the `target` size.

rsmd atom_indices checks fix

---

mdtraj/core/topology.py
tests/test_topology.py

The old `_topology_from_subset` was 
- first creating a new residue anyways (increasing residue count)
- then checking whether it would be added or not to the new topology.
This meant the residue count was increased regardless, leading to inconsistent residue indexing.
Now the residue is only created if the atom is going to be added 
This fixes #1577

bugfix _topology_from_subset correct residue indexing

---

devtools/azure-pipelines-linux.yml
devtools/azure-pipelines-osx.yml

As all new development pipelines are failing, this bumps the `conda` and `conda_build` versions based on [this comment](https://github.com/mdtraj/mdtraj/pull/1586#issuecomment-708903049) from @dwhswenson .
I will cherry pick these over into #1586  and #1584 if this fixes the pipelines

bump conda pins

---

mdtraj/formats/pdb/pdbfile.py

This should solve #1583, 
it should not break `mdtraj` loading as that sets the number to the `Atom.serial` anyway. 
The one thing that I don't know if I am breaking a `pdb` standard here, feel free to close if this is the case.

write out serial instead of index in pdbs

---

pyproject.toml

This implements the solution that was discussed on #1617, found by @rmcgibbo in [this comment](https://github.com/mdtraj/mdtraj/issues/1617#issuecomment-771070431) . It should prevent further issues until python `3.10`
I have only implemented it for python 3.6-3.10 and tested `import mdtraj` for the following installs ( I assume the intermediate numpy installations should also work)
|python| min_numpy| max_numpy| comment
|---|---|---|---|
|3.6|1.14.5|1.19.5| min is bound by scipy, max by pypi
|3.7|1.16.5|1.20.0| min is bound by scipy, import works with scipy warning for numpy==1.14.5
|3.8|1.17.5|1.20.0|
|3.9|1.19.3|1.20.0| 1.19.5 was used for the build but 1.19.3 (absolute minimum numpy for python 3.9) does not complain
Please let me know if you want more python versions supported than …

update numpy build pins

---

mdtraj/reporters/basereporter.py
mdtraj/reporters/hdf5reporter.py

To solve issue #1620. Allow HDF5Reporter to save unwrapped coordinates.

Add enforcePeriodicBox option for HDF5Reporter

---

mdtraj/formats/amberrst.py
mdtraj/formats/hdf5.py
mdtraj/formats/lammpstrj.py
mdtraj/formats/lh5.py
mdtraj/formats/netcdf.py
mdtraj/geometry/contact.py
mdtraj/geometry/dihedral.py
mdtraj/geometry/neighborlist.pyx
mdtraj/geometry/neighbors.pyx
mdtraj/rmsd/_lprmsd.pyx
mdtraj/rmsd/_rmsd.pyx
tests/test_distance.py

A downstream project of mine directly interfaced with this code and our test surface a:
```
DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
This fixes that instance. ~And I did not see more warnings surface when running `py.test` on this repo, but I might be missing some.~
EDIT: did a `grep -r -n "np.int" --include="*.py*"` and will go to the other …

fix a numpy 1.20 depr warning

---

mdtraj/core/topology.py
mdtraj/core/trajectory.py
tests/test_topology.py

When I first used Trajectory.stack I noticed that the resSeq of the added part restarted from 1, this can be quite annoying especially when you are adding one single residue on the top of a file (pdb, gro, ...) , as example if you add one ligand on the top pf a water box, because you would have 2 residues 1.
So I changed Topology.join in order to renumber the new residues according to the last residue of the other topology as default
both Topology.join and Trajectory.stack now accept a new argument keepIds that if set to True will give the old behavior

Topology.join updates resSeq of new residues as default now

---

mdtraj/formats/pdb/pdbfile.py
tests/data/issue_1611.pdb
tests/test_pdb.py

Should solve #1611 while still allowing for #1583 as long as not more than 1 chain is present in the topology.
adds the test cases of #1611 to catch this regression in the future

don't use serials for more than 1 chain

---

mdtraj/geometry/distance.py
tests/test_geometry.py

added select option to compute_center_of_mass to make thing easier and less error prone, the default will act exactly as the older version
I also added it to the  unit test
have also substituted a np.zeros with a np.empty in the same function because it should be faster and doesn't change the result
We were talking about it in the closed issue #1598

added select option to compute_center_of_mass

---

mdtraj/core/trajectory.py
mdtraj/formats/gro.py
mdtraj/formats/pdb/pdbfile.py
tests/test_gro.py
tests/test_load.py
tests/test_pdb.py
tests/test_trajectory.py

Hi, I found myself in the need to load thousands of pdb or gro files all in once and I noticed that the mdtraj.load function can be sped up without losing its high level functionalities
And I also noted that if using pdb or gro files (or in general files in the _TOPOLOGY_EXTS category) the topology gets re-parsed again for each single file.
Therefore I made the PDB and the GRO file parsers able to accept the top argument and therefore re-use the already parsed topology (I would suggest to slowly make the interface more omogeneus by implementing it in all the file parsers in _TOPOLOGY_EXTS, see #1649)
I made the load function able to deal more flexibly with the fact that some parsers may not accept top so if in the future someone implements the top keyword in other parsers it won't be …

Faster load function and more omogeneus file parser interface

---

mdtraj/formats/gro.py

in fact the previous bugfix I did didn't take in consideration the residue renaming of pdb.PDBTrajectoryFile._residueNameReplacements and did therefore create a residue per atom in case of residue renaming. For example in the case of SOL -> HOH renaming
It has been noted in #1658 
And I corrected a small thing in the condition to raise a warning for 2 contiguous residues with the same residue number.

bugfix from previous gro file parsing bugfix

---

mdtraj/core/topology.py
tests/test_topology.py

closes #1646
Now the Topology.from_dataframe methon in topology.py is able to deal with a structure that has many residues with the same resSeq respecting their input order, the function in fact now is much similar to the pdb parser (maybe give a quick check if there is something I haven't considered on how dataframes need to be handled)
I have also added a test
ps if the PR is accepted could it be possible to include it in the 1.9.6 release or is it too late?

now Topology.from_dataframe methon can manage residues with same resSeq

---

mdtraj/reporters/basereporter.py
mdtraj/utils/delay_import.py
mdtraj/utils/unit/__init__.py

Starting in OpenMM 7.6, currently available as a release candidate, the `simtk` namespace is deprecated. This PR makes it so that the new import names (`openmm`, `openmm.app`, and `openmm.unit`) are the first ones tried, while the old names in the `simtk` namespace are used as backups if the new names fail.
I haven't thoroughly tested the changes to `import_` yet, but I have checked that I can at least import MDTraj in both an OpenMM 7.6 environment and an OpenMM 7.5 environment, and I don't see the warning about the import name changing when I do that import in 7.6.

New OpenMM imports

---

examples/test_examples.py

When looking into #1683 I got hit with a bunch of:
```
________________________________ test_example_notebook[rmsd-drift.ipynb] ________________________________
example_fn = 'rmsd-drift.ipynb'
def test_example_notebook(example_fn):
with open(example_fn) as f:
nb = nbformat.reads(f.read(), nbformat.NO_CONVERT)
>       run_notebook(nb)
/home/sander/github_files/mdtraj/examples/test_examples.py:69: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
nb = {'cells': [{'cell_type': 'code', 'execution_count': None, 'metadata': {}, 'outputs': [], 'source': 'from __future__ im...'nbconvert_exporter': 'python', 'pygments_lexer': 'ipython3', 'version': '3.5.2'}}, 'nbformat': 4, 'nbformat_minor': 1}
def run_notebook(nb):
km = KernelManager() …
```

[Tests] Fix code for running jupyter notebooks to work with latest vesions of jupyter

---

mdtraj/rmsd/include/util_arm.h

[While trying to build for M1 chips](https://github.com/conda-forge/mdtraj-feedstock/pull/37) this patch was required to get the build to work. (originally implemented by @mattwthompson)

Patch util_arm.h for M1

---

mdtraj/core/trajectory.py

using `filename_or_filenames.pop(0)` leads to a change of the filename list which propagates back into the outer scope and is (in my opinion) quite unexpected, i.e., handing in a list of filenames, that list is suddenly shorter by 1 after a call to `mdtraj.load`. This small change uses slicing rather than `pop` which as an added benefit also supports tuples (which do not possess `pop`).

Avoid side effects in mdtraj.load

---

docs/atom_selection.rst

I deleted unnecessary "`" in the code-block highlight.

Fix typo in docs

---

mdtraj/geometry/distance.py
tests/test_distance.py

This adds a lower level interface to the existing `compute_distances`
function in `geometry.distance` that allows the user to pass in only
the position coordinates (and box information if needed) rather than
only having the Trajectory interface.
This allows for implementing algorithms which can easily add in
virtual atoms (such as centers of mass) without needing to actually go
through changing the Topology object of a Trajectory.

Adds lower-level `compute_distances_core` function

---

mdtraj/core/topology.py

[Disclaimer: @rmcgibbo I'm well aware of your note on current project status. Thanks so much for mdtraj! I'm posting this because I think it's the best place to do it, even if you can't do anything with it at the moment. Just hoping it makes it into whatever next release you can do, if you plan such a thing at all.]
The previous logic didn't detect a new residue unless resSeq or resname had changed. 
This left out a situation I just came across: a pdb where two subsequent chains, consisting of one residue each, have the same resname and resSeq. Using from_dataframe on them, the second chain gets correctly created, but its atoms get assigned to the previous residue (of the previous chain) since the residue hadn't been updated. 
The PDB in question is …

[core.Topology.from_dataframe] BUGFIX: force new residue when creating new chain

---

mdtraj/core/topology.py

As per issue #1753 a fix so that a warning is raised if atom_indices are not monotonically increasing. There is no other tweaking, so existing behaviour continues: atom_indices like [5,4,3,2,1] will be accepted but the resulting topology will be bogus, and atom_indices like [1,2,3,3,4] will lead to a ValueError later in the code, when the subsetted coordinates and topology are found not to match up.

Warn if atom_indices are not monotonically increasing

---

.github/workflows/main.yaml

Pinning nix to 2.13.3 (or install-nix-action@v16 to v20)  
See blow for references:
https://github.com/cachix/install-nix-action/issues/161 
https://github.com/cachix/cachix-action/issues/144

fix bugs by nix-2.15

---

README.md

Starting a PR where I'm updating the MDTraj README to indicate the transition to new maintainers (and welcoming continued support/contributions from folks). Thoughts/edits/discussions welcome!
For now at least the README is the only change made. I may have to dig around the docs a bit to ensure that appropriate contact info is placed there as well.

Maintainer announcement update (to README, etc.)

---

pyproject.toml

Older numpy versions pinned were causing issues when those numpy versions were not compatible with newer mac platform.
Instead, let's use https://github.com/scipy/oldest-supported-numpy which does the right thing for most known build envs.

Use oldest-supported-numpy instead of numpy version pinning for build system

---

devtools/conda-envs/test.yaml
pyproject.toml

Band-aid for #1800, which should be followed-up by a proper fix.
Version 3.0 (!) was released, but the current source code is only compatible with versions 0.29.x

Constrain `cython=0.29`

---

docs/whatsnew.rst

I think we should put out a quick release, mostly to resolve #1800 without folks needing to read up on an issue and add another constraint into their build system. There have only been a couple of other merges since then, only toolkit/docs and no substantive changes to the source code.
I can take care of this, but not until tomorrow or possibly late tonight at the earliest (MDTraj is not my day job).

Add v1.9.9 release notes

---

devtools/conda-envs/test.yaml
mdtraj/formats/gsd.py

Address #1825, update syntax in `gsd.py` to match with the latest GSD 3 open syntax (https://gsd.readthedocs.io/en/stable/python-module-gsd.hoomd.html).

Update syntax for GSD reader/writer

---

.github/workflows/main.yaml
examples/test_examples.py
mdtraj/formats/amberrst.py
mdtraj/formats/netcdf.py
mdtraj/nmr/shift_wrappers.py
setup.py
tests/test_dihedral.py
tests/test_dssp.py
tests/test_hbonds.py
tests/test_mol2.py
tests/test_netcdf.py
tests/test_psf.py

The `distutils` module has been removed from Python 3.12 per [PEP 632](https://peps.python.org/pep-0632/).

Drop distutils usage and add Python 3.12 tests

---

.github/workflows/main.yaml
devtools/conda-envs/test.yaml

Free runners include two cores these days and tests take a few minutes, so this should speed things up.

Run tests in parallel

---

.github/workflows/main.yaml

Just in case any of the maintainers are wondering, GitHub Action runner images for `macos-latest` has shifted to `macos-14-arm64` a few days ago (from `macos-12`, which is x86-64). That's probably causing the fails in the scheduled CI.
Changing from `macos-latest` to `macos-13` should fix this for the time being, until the arm64 workflows are ready. `macos-13` is the last "standard" (i.e., free) x86-64 runner image from GitHub.

CI macos-latest fix

---

mdtraj/formats/netcdf.py
mdtraj/utils/delay_import.py

This PR addresses #1831.
I've adopted the strategy suggested by the Issue author, based on an approach taken in ParmEd and MDAnalysis, to use netCDF4 if installed and fall back to SciPy netCDF if not installed.
I based the code for netCDF4 on the original version in the code base. It used netCDF4 before SciPy netCDF, PR that changed it here - https://github.com/mdtraj/mdtraj/pull/360/files
Here is a small demo notebook that demonstrates both backends being used: https://github.com/janash/mdtraj-netcdf/blob/main/openmm.ipynb
I also updated the message about `netCDF4` to give information about `conda` and have an updated URL
One thing I'm not quite sure about is using `import_`. It gives a very verbose message, but it's not actually causing an Exception with my current use, so may be …

Sets netCDF4 as default in NetCDFTrajectoryFile, fallback to scipy

---

mdtraj/geometry/include/sasa.h
mdtraj/geometry/sasa.py
mdtraj/geometry/src/_geometry.pyx
mdtraj/geometry/src/sasa.cpp
tests/test_sasa.py

A little holiday coding for something I had working locally for 3 years and never pushed (#[PR1671](https://github.com/mdtraj/mdtraj/pull/1671) was closed as stale/wontfix). It's been crucial for all my projects all this time.
Here's the original PR message:
> Limit the SASA computation to some atoms of interest via atom_indices when calling md.shrake_rupley
> 
> The excluded atoms are still considered as potential surface accessibility blockers, but their own SASA doesn't get computed and gets set to zero instead.
> 
> This is particularly helpful for membrane-embedded proteins where you want the lipids "there" but you don't really care about their SASA.
>  
I followed @rmcgibbo 's suggestion for the c++ implementation. 
The return SASA-value for 'excluded' atoms/residues is set to …

Add atom selection via atom_indices to SASA computation (try #2, three years after)

---

pyproject.toml

I was a bit surprised to see this dependency still in the build-system part as it also defines `numpy>2`.
It is officially [deprecated](https://github.com/scipy/oldest-supported-numpy?tab=readme-ov-file#deprecation-notice-for-numpy-20) and the backwards compatibility issue has been solved by numpy since version `1.25` (before that oldest-supported-numpy was needed for build stability).
This is what the [current numpy docs](https://numpy.org/devdocs/dev/depending_on_numpy.html#build-time-dependency) say:
> By default, NumPy will expose an API that is backwards compatible with the oldest NumPy version that supports the currently oldest compatible Python version. NumPy 1.25.0 supports Python 3.9 and higher and NumPy 1.19 is the first version to support Python 3.9. Thus, we guarantee that, …

remove deprecated oldest-supported-numpy

---

mdtraj/geometry/internal.py

#1907 
Since it's an easy fix, I've gone ahead and made them.
`filter` in python 3 now returns a `generator` instead of a `list`, but shouldn't matter in since we're using it in a `for` loop.
`xrange` is only used in `for` loops, so a `range` should work the same.
Can confirm the error doesn't show up, but I haven't used mdinspect before.

remove remaining instances of six

---

devtools/conda-envs/test.yaml
docs/requirements.txt
mdtraj/formats/xtc/trr.pyx
mdtraj/formats/xtc/xtc.pyx

I'm trying to reduce some of the deprecation warnings we get in the mosdef packages, and one of them was from mdtraj's use of `xdrlib`.  https://github.com/mdtraj/mdtraj/issues/1818 mentions using the `mda_xdrlib` package as a replacement, which this PR does.

Replace `xdrlib` with `mda_xdrlib`

---

setup.py

I was getting the following error:
```bash
conda create -yq -n mdtraj-missing-xdr python=3.11 pip
conda activate mdtraj-missing-xdr
python -m pip install git+https://github.com/mdtraj/mdtraj.git
python -c "import mdtraj"
```
```pytb
File "<string>", line 1, in <module>
File "/Users/dwhs/miniforge3/envs/mdtraj-missing-xdr/lib/python3.11/site-packages/mdtraj/__init__.py", line 33, in <module>
from mdtraj.core.trajectory import (
File "/Users/dwhs/miniforge3/envs/mdtraj-missing-xdr/lib/python3.11/site-packages/mdtraj/core/trajectory.py", line 34, in <module>
from mdtraj.formats import (
File "/Users/dwhs/miniforge3/envs/mdtraj-missing-xdr/lib/python3.11/site-packages/mdtraj/formats/__init__.py", line 13, in <module>
from mdtraj.formats.trr import …
```

Add mda-xdrlib to setup.py requirements

---

devtools/conda-envs/test.yaml
docs/requirements.txt
mdtraj/formats/xtc/trr.pyx
mdtraj/formats/xtc/xtc.pyx
setup.py

Following up the discussion of #1818, this PR removes the unused Python `xdrlib`, as only the internal C `xdrlib` is used. Closes #1818

Remove unused Python xdrlib import

---

devtools/conda-envs/test.yaml
mdtraj/rmsd/_lprmsd.pyx
mdtraj/rmsd/_rmsd.pyx
pyproject.toml

* We needed this fix internally to make mdtraj work with Cython 3.0.
* This fixed it, however, we build rdkit ourselves using Blaze (Bazel), so this fix might not be applicable upstream.

Fix RMSD externs to be compatible with Cython 3.0.

---

docs/whatsnew.rst

Here's the GitHub-generated Markdown blob:
```
* Issue 1829 by @CharlieLaughton in https://github.com/mdtraj/mdtraj/pull/1841
* Add atom selection via atom_indices to SASA computation (try #2, three years after) by @gph82 in https://github.com/mdtraj/mdtraj/pull/1844
* [WIP] ReadTheDocs migration by @sukritsingh in https://github.com/mdtraj/mdtraj/pull/1888
* Fix netCDF file loading to no longer import scipy (and add netCDF to CI reqs) by @sukritsingh in https://github.com/mdtraj/mdtraj/pull/1894
* AST-related modifications by @jeremyleung521 in https://github.com/mdtraj/mdtraj/pull/1898
* Allow appending to HDF5 files using `trajectory.save_hdf5` by @sukritsingh in https://github.com/mdtraj/mdtraj/pull/1899
* Mock-testing dependency absence for netCDF4 by @jeremyleung521 in …
```

Make 1.10.1 release notes

---

pyproject.toml
setup.py

Proabably should've done this when we dropped `oldest-supported-numpy` and added numpy 2 support but here it is. 
This ensures numpy 2 is used during build time so the compiled files are compatible with numpy 1 and 2. numpy>=1.25 is required at run time so the C-API exporting works.
https://github.com/scipy/oldest-supported-numpy

pin numpy>=1.25 at run time, numpy>=2.0 at build time for numpy C-API

---

.github/workflows/main.yaml
mdtraj/core/topology.py
tests/test_topology.py

Hi all,
This PR perserves `chain_id`s when going to/from openmm topologies. It is pretty analogous to https://github.com/mdtraj/mdtraj/pull/1858. 
This allows preservation of chain IDs when reading/writing PDBx/mmCIF files, since, for reading, `PDBXTrajectoryFile.__init__` uses `from_openmm`, leveraging openmm's `PDBxFile` object that maintains chain IDs itself,  and, for writing, the `PDBxTrajectoryFile.write` method uses `to_openmm`.
The `topology` property, and the `topology.setter` in `HDF5TrajectoryFile` need extra work to carry through chain IDs in topologies there since they use a `topology_dict` that doesn't carry through chain IDs.

Preserve `chain_ids` for `to_openmm` and `from_openmm`

---

devtools/conda-envs/test.yaml
tests/test_distance.py

A few tests were failing on one specific configuration (one python version, macos) and require manual restarting. I added `pytest-rerunfailures` as a pytest plugin, which would automatically rerun the tests 3 times before officially declaring a failure. 
https://github.com/jeremyleung521/mdtraj/actions/runs/13057906340/job/36433449570
https://github.com/mdtraj/mdtraj/actions/runs/12101259345/job/33740887047
Also had to restart `test_superpose_refinds` FOUR TIMES to get it working. Not sure what that was about. Leaving that be for now.
https://github.com/mdtraj/mdtraj/actions/runs/12966061236/job/36247585956

add flaky to a few test_distance tests

---

mdtraj/rmsd/_lprmsd.pyx

Hi all,
The cython file `_lprmsd.pyx` imports `scipy.spatial.distance`, even though it doesn't use anything from `scipy` at all. This prevents any submodule of mdtraj from being imported without scipy installed, since mdtraj's `__init__.py` imports lprmsd for `__all__` . 
It also appears that care was used to _selectively_ import scipy in various places throughout the repository:
- [here, only in smooth()](https://github.com/mdtraj/mdtraj/blob/76a7563dc708c7a2c3918c0b506b3eaaca34272d/mdtraj/core/trajectory.py#L2142)
- [here, only in AmberNetCDFRestartFile](https://github.com/mdtraj/mdtraj/blob/76a7563dc708c7a2c3918c0b506b3eaaca34272d/mdtraj/formats/amberrst.py#L540-L545)
- [here, only inside kabsch_sander()](https://github.com/mdtraj/mdtraj/blob/76a7563dc708c7a2c3918c0b506b3eaaca34272d/mdt …

Remove scipy import in `_lprmsd.pyx` to make mdtraj submodules importable without scipy

---

tests/conftest.py
tests/test_distance.py
tests/test_dssp.py
tests/test_pdb.py

Allowing tests that pull pdb off rcsb.org to rerun up to 3 times. My current theory is that the pdb pulled is corrupted, leading to failed tests. 
This is an error observed in #1986 and #1983 (among other places). (Somehow not reproducible locally though)

add flaky/rerun-failures to tests that require pulling off a pdb

---

devtools/conda-envs/test.yaml
mdtraj/utils/delay_import.py
setup.py

Removing netCDF4 as a hard dependency (see https://github.com/mdtraj/mdtraj/issues/1897).
While I was at it, I added in `mdtraj[tests]` and `mdtraj[optional]`, which should allow you to install most of the other dependencies without having to resort to the test conda env recipe, and `pip install mdtraj[all]` should install both sets. I also updated the `delay_import` documentation to remove `scripttest` (not used anymore) and `scipy` (a hard dependency now).
I believe we are dropping python 3.9 (EOL later this year) so did that in the metadata as well.

Remove netCDF4 dependency, set up PyPI build variants

---

mdtraj/formats/arc.py
tests/test_arc.py
tests/test_trajectory.py

Been recently working on `.arc` trajectory files (yay Tinker). While the file itself contains _some_ information on topology, it does not have residue information. This means all atoms are [funneled into a single residue](https://github.com/mdtraj/mdtraj/blob/main/mdtraj/formats/arc.py#L100-L103). ([actual code](https://github.com/mdtraj/mdtraj/blob/main/mdtraj/formats/arc.py#L353-L356))
This PR adds in the functionality to feed in a topology (file name, trajectory objects, or topology objects) to `load_arc()`, allowing users to better read in arc trajectory files for analysis. Most of the code is essentially modeled off of the [NetCDF trajectory loader](https://github.com/mdtraj/mdtraj/blob/main/mdtraj/formats/netcdf.py), which requires a topology. Existing behavior for not feeding in a …

Allow ArcTrajectoryFile to optionally take topology

---

mdtraj/core/topology.py
tests/test_topology.py

This PR is to addressing issue #2001 
1. Atoms with formal charges are now supported by `to_dataframe()` and `from_dataframe()`
2. Unit tests for these two functions are provided

Add formal charge to the `to_dataframe()` and `from_dataframe()` methods

---

tests/conftest.py
tests/test_distance.py

The generation of a random `ptraj` and other associated variables for `test_distances.py` are currently at the top of the test file. Unfortunately, some tests below share the same variable names (e.g. `xyz`), which means they could be overwritten when the tests are run out of order using `pytest-xdist`. My hypothesis is that this is [causing some](https://github.com/jeremyleung521/mdtraj/actions/runs/13777969584/job/38530872667#step:6:3054) [flaky behavior in the CI](https://github.com/mdtraj/mdtraj/actions/runs/13732317066/job/38411437988#step:6:3026).
I moved all that to `conftest.py` as fixture class variables, which should prevent those variables from being overwritten. Some egregious errors include the parts of the `xyz` array being rewritten [into …

move rng/ptraj generation for distance tests into fixture

---

mdtraj/core/selection.py

This removes the arbitary arguments passed to `ast.Name` and `ast.Call` in the selection module and addresses: https://github.com/mdtraj/mdtraj/issues/1982. 
Support for arbitrary arguments will be deprecated in Py3.15.  
Changes are self-explanatory. 
Before and after tests are shown below: 
```bash
============================= test session starts ==============================
platform darwin -- Python 3.13.2, pytest-8.3.5, pluggy-1.5.0 -- /Users/*****/.local/share/virtualenvs/mdtraj-tICb6qJl/bin/python
cachedir: .pytest_cache
rootdir: /Users/*****/Library/CloudStorage/GoogleDrive-*****/My Drive/Software/mdtraj
configfile: pytest.ini
plugins: xdist-3.6.1
collecting ... collected 25 items
tests/test_selection.py::test_range PASSED                               [  4%] …
```

refactor: removed arbitrary arguments from AST module classes

---

mdtraj/core/trajectory.py
mdtraj/formats/arc.py
mdtraj/formats/hdf5.py

Currently, loading `.h5` and `.mol2` files with `mdtraj.load()` will always return a `UserWarning`, even though no `top` kwarg is passed. This is because the topology is loaded twice for these file types (these loaders don't take the `top` argument), and the topology from the first load triggers the `UserWarning` right before the second successful topology load.
More precisely, the two topology loads happen 
A) once during [topology parsing](https://github.com/mdtraj/mdtraj/blob/main/mdtraj/core/trajectory.py#L398) and 
B) once during this [try/except block](
https://github.com/mdtraj/mdtraj/blob/main/mdtraj/core/trajectory.py#L442-L444) where topology is discarded (because a `top` argument is given) and the topology is reread again. 
This can lead to a large performance hit for large …

Fix Topology double-loading for HDF5 and MOL2 (+ remove false-positive UserWarning)

---

mdtraj/core/topology.py
tests/test_topology.py

This addresses https://github.com/mdtraj/mdtraj/issues/1900
When `delete_atom_by_index` is called the bond list is now updated so that bonds involving the atom are removed.  
I've added a  test involving Ala3 . 
Tests for topology: 
```bash
tests/test_topology.py::test_topology_openmm SKIPPED (needs OpenMM)                                     [  3%]
tests/test_topology.py::test_topology_openmm_preserve_chain_id_when_specified SKIPPED (needs OpenMM)    [  6%]
tests/test_topology.py::test_topology_openmm_roundtrip_chain_id SKIPPED (needs OpenMM)                  [  9%]
tests/test_topology.py::test_topology_openmm_preserve_chain_id_even_when_empty SKIPPED (needs OpenMM)   [ 12%]
tests/test_topology.py::test_topology_openmm_boxes SKIPPED (needs OpenMM)                               [ 15%] …
```

bugfix: delete_atom_by_index updates bond list

---

pyproject.toml
tests/test_contact.py
tests/test_drid.py
tests/test_geometry.py
tests/test_gro.py
tests/test_pdb.py
tests/test_topology.py
tests/test_trajectory.py

This removes the following warnings from tests. Part of a de-cluttering process.
These are hidden:
```
/Users/runner/micromamba/envs/mdtraj-test/lib/python3.13/site-packages/mdtraj/core/topology.py:97: UserWarning: atom_indices are not monotonically increasing
warnings.warn("atom_indices are not monotonically increasing")
```
```
tests/test_utils.py::test_ensure_type_11
/home/runner/micromamba/envs/mdtraj-test/lib/python3.13/site-packages/mdtraj/utils/validation.py:123: TypeCastPerformanceWarning: Casting  dtype=int64 to <class 'numpy.float32'> 
warnings.warn(
```
```
tests/test_dssp.py::test_1[1vii.pdb]
tests/test_gro.py::test_read_write
tests/test_gro.py::test_read_write_precision
tests/test_gro.py::test_load
tests/test_shape.py::test_principal_moments …
```

limit warnings in tests

---

docs/whatsnew.rst

Release notes for v1.11.0! 
There were a few PRs that had dual contributors, even though these didn't show up in the generated release notes (#2013, #2023,  #1771). I added both GitHub usernames to the list item for this and the names of both people to the bottom list of contributors. I also removed all pre-commit and dependabot commits from the "What's New" list.

Add release notes for v1.11.0

---

mdtraj/geometry/src/image_molecules.pxi
tests/test_trajectory.py

#1975 
Not sure if it actually speeds up anything or if this actually did anything, but the "performance hints" are gone during compilation.

speedup some cython functions by enforcing nogil for exceptions (add return code)

---

mdtraj/geometry/shape.py

Fix for equation rendering on the documentation page for [`asphericity`](https://mdtraj.readthedocs.io/en/latest/api/generated/mdtraj.asphericity.html) and [`relative_shape_anisotropy`](https://mdtraj.readthedocs.io/en/latest/api/generated/mdtraj.relative_shape_antisotropy.html) in `mdtraj/mdtraj/geometry`.

Minor bug fix for documentation equations 

---

.github/dependabot.yml
.pre-commit-config.yaml

As per https://github.com/mdtraj/mdtraj/pull/2080#issuecomment-3267497653, we're updating pre-commit monthly. Also doing dependabot updates weekly, since we really don't need every minuscule point update.
Doing it less frequently allow updates to stack.

update dependabot weekly and pre-commit monthly

---

.github/workflows/build.yaml
.github/workflows/main.yaml
devtools/conda-envs/test.yaml

Thought I was in my own fork but whatever.
Our testing is currently bottlenecked by the lack of a py3.14 compatible release of openmm. I dropped `openmm` here for the time being and things are working fine (i.e. tests run and all pass).
I'll update the PR after Python 3.14 has officially released next Tuesday, then we can merge this in, along with https://github.com/conda-forge/mdtraj-feedstock/pull/82.
EDIT: `cibuildwheel` works fine
https://github.com/jeremyleung521/mdtraj/actions/runs/18227642437/job/51902948368

Python3.14 testing and building
